
sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm i

script:
  - ng build

git:
  depth: 1

notifications:
  slack: frontnotend:KW0DeBHIDUpJpOPYaNx5dAqd
